added fastcgi cache and changed proxy cache

diff --git a/bin/createdirs b/bin/createdirs
--- a/bin/createdirs
+++ b/bin/createdirs
@@ -8,8 +8,11 @@ echo "Checking for logs directory"
 echo "Checking for cache/l1_cache directory"
 [ -d "$sdir/cache/l1_cache" ] && echo "$sdir/cache/l1_cache directory exists" || mkdir -p "$sdir/cache/l1_cache" || { echo "Failed to create directory: cache/l1_cache"; exit; }
 
-echo "Checking for cache/l2_cache directory"
-[ -d "$sdir/cache/l2_cache" ] && echo "$sdir/cache/l2_cache directory exists" || mkdir -p "$sdir/cache/l2_cache" || { echo "Failed to create directory: cache/l2_cache"; exit; }
+echo "Checking for cache/l2_proxy directory"
+[ -d "$sdir/cache/l2_proxy" ] && echo "$sdir/cache/l2_proxy directory exists" || mkdir -p "$sdir/cache/l2_proxy" || { echo "Failed to create directory: cache/l2_proxy"; exit; }
+
+echo "Checking for cache/l2_fastcgi directory"
+[ -d "$sdir/cache/l2_fastcgi" ] && echo "$sdir/cache/l2_fastcgi directory exists" || mkdir -p "$sdir/cache/l2_fastcgi" || { echo "Failed to create directory: cache/l2_fastcgi"; exit; }
 
 echo "Checking for temp/l1_temp directory"
 [ -d "$sdir/temp/l1_temp" ] && echo "$sdir/temp/l1_temp directory exists" || mkdir -p "$sdir/temp/l1_temp" || { echo "Failed to create directory: temp/l1_temp"; exit; }
