added verbose messages to bin/setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -27,16 +27,28 @@ then
     exit
 fi
 
+echo "Checking for logs directory"
 [ -d "$sdir/../logs" ] || mkdir "$sdir/../logs" || { echo "Failed to create directory logs"; exit; }
+
+echo "Checking for cache/l1_cache directory"
 [ -d "$sdir/../cache/l1_cache" ] || mkdir -p "$sdir/../cache/l1_cache" || { echo "Failed to create directory: cache/l1_cache"; exit; }
+
+echo "Checking for cache/l2_cache directory"
 [ -d "$sdir/../cache/l2_cache" ] || mkdir -p "$sdir/../cache/l2_cache" || { echo "Failed to create directory: cache/l1_cache"; exit; }
 
+echo "Enabling ip_forward"
 echo "1" > /proc/sys/net/ipv4/ip_forward
 
-ip rule add fwmark 1 lookup 100 || { echo "Failed to add fwmark"; exit; }
+echo "Adding new route lookup table"
+ip rule add fwmark 1 lookup 100 || { echo "Failed to add route lookup table"; exit; }
 
+echo "Adding local route to new table"
 ip route add local 0.0.0.0/0 dev lo table 100 || { echo "Failed to add local route"; exit; }
 
+echo "Adding marking firewall rule for host: 192.168.74.10/32 port: 2598"
 iptables -t mangle -A PREROUTING -p tcp -s 192.168.74.10/32 --sport 2598 -j MARK --set-xmark 0x1/0xffffffff || { echo "Failed to add rule for port 2598"; exit; }
 
+echo "Adding marking firewall rule for host: 192.168.74.10/32 port: 443"
 iptables -t mangle -A PREROUTING -p tcp -s 192.168.74.10/32 --sport 443  -j MARK --set-xmark 0x1/0xffffffff || { echo "Failed to add rule for port 443"; exit; }
+
+echo "setup complete"
